title: Next Time Space - Analligence
description: Free open source analitics bussiness tool to find customer engegment. Create catalogs, segment, see metrics and make decision based on analytics metrics.
show_downloads: true
theme: jekyll-theme-architect
